# Generated by Django 5.1.4 on 2025-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('status', models.CharField(db_column='Status', max_length=255)),
                ('time', models.CharField(db_column='Time', max_length=255)),
                ('newrecords', models.IntegerField(db_column='NewRecords')),
            ],
            options={
                'db_table': 'Event_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KevCatalog',
            fields=[
                ('cveid', models.TextField(blank=True, db_column='cveID', null=True)),
                ('vendorproject', models.TextField(blank=True, db_column='vendorProject', null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('vulnerabilityname', models.TextField(blank=True, db_column='vulnerabilityName', null=True)),
                ('dateadded', models.TextField(blank=True, db_column='dateAdded', null=True)),
                ('shortdescription', models.TextField(blank=True, db_column='shortDescription', null=True)),
                ('requiredaction', models.TextField(blank=True, db_column='requiredAction', null=True)),
                ('duedate', models.TextField(blank=True, db_column='dueDate', null=True)),
                ('knownransomwarecampaignuse', models.TextField(blank=True, db_column='knownRansomwareCampaignUse', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cwes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'KEV_Catalog',
                'managed': False,
            },
        ),
    ]
